#当三个文件中有配置信息冲突时,优先级是:properties>yaml>yml,也就是properties里配置的内容会覆盖另外两个的配置

server:
  port: 8080
  tomcat:
    min-spare-threads: 10 #最小线程数 default 10
    max-threads: 200 #最大线程数 default 200
    accept-count: 100 #最小线程用完了的等待队列大小 default 100
    max-connections: 10000 #最大并发数 default 10000

    accesslog:
      buffered: true
      #      directory: C:/logs
      directory: /root/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true


# mysql configuration
spring:
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://47.100.213.205:3306/monitor?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    #    url: jdbc:mysql://127.0.0.1:3306/monitor?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
      #    password: admin
    password: Mydb6.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2 #初始化连接个数
      min-idle: 5 #最小空闲连接个数
      max-active: 20 #最大连接个数
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      time-between-eviction-runs-millis: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 3000  #配置一个连接在池中最小生存的时间，单位是毫秒


mybatis:
  type-aliases-package: com.monitor.pojo
  mapper-locations: classpath*:com/monitor/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

